version: '3.3'
services:
  client0:
    extra_hosts:
      combiner:
    environment:
      - GET_HOSTS_FROM=dns
    image: "imseg2"
    build:
      context: .
    working_dir: /app
    command: /venv/bin/fedn run client -in client.yaml
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      - ./data/:/app/data:ro #mount as READ ONLY
      - ./client.yaml:/app/client.yaml

